"awp_l337sk337"
{
	"name"				 "awp_l337sk337"
	"t_arms" 				"models/weapons/t_arms_pirate.mdl"
	"ct_arms" 				"models/weapons/ct_arms_st6.mdl"
	"t_models"
	{
		"tm_pirate" ""
		"tm_pirate_variantA" ""
		"tm_pirate_variantB" ""
		"tm_pirate_variantC" ""
		"tm_pirate_variantD" ""
	}
	"ct_models"
	{
		"ctm_st6" ""
		"ctm_st6_variantA" ""
		"ctm_st6_variantB" ""
		"ctm_st6_variantC" ""
		"ctm_st6_variantD" ""
	}
}